version: "3.9"

services:
  server:
    build:
      context: .
      target: development
    command: sh -c "npm install && npm run start:dev"
    profiles:
      - dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  test:
    build:
      context: .
      target: development
    command: sh -c "npm install && npm run test:e2e:cov"
    profiles:
      - test
    volumes:
      - .:/usr/src/app
