version: "3.9"

services:
  server:
    build:
      context: .
      target: development
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
